### ISSUE TITLE
Improve tracking and POI commands

### ISSUE THREAD

**Issue by virtualnaut** [virtualnaut/slime-priest#6]
The usability of the tracking and POI commands isn't great, so the following changes should be made:

- [ ] Add a command to check the status of the tracking
  - Would return an embed showing status out of 'Disabled' (the command isn't runnning), 'Idle' (no user is being tracked) or 'Active' (a user is selected and the command is running)
- [ ] If no user is given on the `~track` command, attempt to set the tracked user to the POI associated with the user that sent the message
- [ ] Add a command to list the current people of interest

**Comment by virtualnaut** [comment]
Added warning message for if the current user is already the tracked user.
